import type { Metadata } from "next";
import { Header, SearchFocusedOverlay } from "@/components/shared";
import AppContextProvider from "@/contexts/AppContextProvider";

export const metadata: Metadata = {
  title: "Next Pizza | Главная",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {

  return (
    <AppContextProvider>
      <Header />
      <SearchFocusedOverlay />
      <main>{children}</main>
    </AppContextProvider>
  );
}
