import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared";

const nunito = Nunito({
    weight: [],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Next Pizza | Главная",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${nunito.className} antialiased`}>
                <Header />

                {children}
            </body>
        </html>
    );
}
