import { CheckoutHeader } from "@/components/shared";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Next Pizza | Корзина",
    description: "Generated by create next app",
};

export default async function Layout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    
    return (
        <div className="bg-[#F4F1EE] min-h-screen">
            <CheckoutHeader />
            <main>{children}</main>
        </div>
    );
}
